# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-settings
  namespace: opennms
data:
  DOMAIN: azure.agalue.net
  TIMEZONE: America/New_York
  OPENNMS_INSTANCE_ID: K8S
  CASSANDRA_CLUSTER_NAME: OpenNMS
  CASSANDRA_DC: Main
  CASSANDRA_REPLICATION_FACTOR: "2"
  ELASTIC_REPLICATION_FACTOR: "2"
  ELASTIC_INDEX_STRATEGY_FLOWS: daily
  KAFKA_NUM_PARTITIONS: "6"
  MINION_LOCATION: Kubernetes
