# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - The cassandra user (uid: 999, gid: 999) cannot be used in OpenShift by default.
# - Make sure to take appropriate actions when stopping or decomissioning (shrink cluster).
# - Cassandra expects to have very fast disks for the PVC to avoid performance issues.
#
# TODO:
# - Take a look at https://github.com/instaclustr/cassandra-operator
# - Take a look at https://github.com/scylladb/scylla-code-samples/tree/master/kubernetes-scylla

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: opennms
  labels:
    app: cassandra
data:
  # Be able to access Cassandra through JMX (for cassandra-reaper and for monitoring purposes)
  jmxremote.password: |+
    monitorRole QED
    controlRole R&D
    cassandra cassandra
  # Enable G1GC as the performance tests on the field have proven good results.
  jvm.options: |+
    -ea
    -XX:+UseThreadPriorities
    -XX:ThreadPriorityPolicy=42
    -XX:+HeapDumpOnOutOfMemoryError
    -Xss256k
    -XX:StringTableSize=1000003
    -XX:+AlwaysPreTouch
    -XX:-UseBiasedLocking
    -XX:+UseTLAB
    -XX:+ResizeTLAB
    -XX:+UseNUMA
    -XX:+PerfDisableSharedMem
    -Djava.net.preferIPv4Stack=true
    -XX:+UseG1GC
    -XX:G1RSetUpdatingPauseTimePercent=5
    -XX:MaxGCPauseMillis=500
    -XX:+PrintGCDetails
    -XX:+PrintGCDateStamps
    -XX:+PrintHeapAtGC
    -XX:+PrintTenuringDistribution
    -XX:+PrintGCApplicationStoppedTime
    -XX:+PrintPromotionFailure
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=10
    -XX:GCLogFileSize=10M

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
  - port: 7000
    name: intra-node
  - port: 7001
    name: tls-intra-node
  - port: 7199
    name: jmx
  - port: 9042
    name: cql
  selector:
    app: cassandra

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 600
      securityContext: # In order to be able to write data as non-root on the volumes
        fsGroup: 999 # Default cassandra user
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: cassandra
        image: cassandra:3.11.5
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: LOCAL_JMX
          value: 'false'
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: MAX_HEAP_SIZE
          value: $(MEM_TOTAL_MB)m
        - name: HEAP_NEWSIZE
          value: $(MEM_TOTAL_MB)m
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.opennms.svc.cluster.local
        - name: CASSANDRA_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CLUSTER_NAME
              name: common-settings
        # The following 3 variables are required to use NetworkTopologyStrategy with the Newts keyspace
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        - name: CASSANDRA_DC
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_DC
              name: common-settings
        - name: CASSANDRA_RACK
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # TODO spec.nodeName seems more accurate, but an affinity policy might be better.
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        volumeMounts:
        - name: data
          mountPath: /cassandra_data
        - name: cassandra-config
          mountPath: /etc/cassandra/jmxremote.password
          subPath: jmxremote.password
        - name: cassandra-config
          mountPath: /etc/cassandra/jvm.options
          subPath: jvm.options
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        securityContext:
          runAsUser: 999
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'if [[ $(nodetool -u cassandra -pw cassandra status -r | grep $HOSTNAME) == *"UN"* ]]; then exit 0; else exit 1; fi'
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: cql
          initialDelaySeconds: 90
          periodSeconds: 60
      volumes:
      - name: cassandra-config
        configMap:
          name: cassandra-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
