# @author Alejandro Galue <agalue@opennms.org>
#
# Warning: this excludes Cassandra to reduce the overhead on Minikube

---
bases:
- ../manifests

patchesStrategicMerge:
- patches/cassandra.reaper.yaml
- patches/cassandra.yaml
- patches/elastic-hq.yaml
- patches/elasticsearch.data.yaml
- patches/elasticsearch.master.yaml
- patches/grafana.yaml
- patches/hasura.yaml
- patches/kafka.yaml
- patches/kibana.yaml
- patches/opennms.alec.yaml
- patches/opennms.core.yaml
- patches/opennms.minion.yaml
- patches/opennms.sentinel.yaml
- patches/opennms.ui.yaml
- patches/postgresql.yaml
- patches/zookeeper.yaml
